import 'modules/admin-lte/plugins/jQueryUI/jquery-ui.min'
import 'modules/admin-lte/plugins/fastclick/fastclick'
import 'modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min'
import 'modules/admin-lte/plugins/datatables/jquery.dataTables.min'
import 'modules/admin-lte/dist/js/app.min'
import 'modules/admin-lte/plugins/jQuery/jquery-2.2.3.min'
import 'modules/admin-lte/plugins/datepicker/bootstrap-datepicker'
import 'modules/admin-lte/plugins/colorpicker/bootstrap-colorpicker.min'

import 'modules/admin-lte/plugins/input-mask/jquery.inputmask'
import 'modules/admin-lte/plugins/input-mask/jquery.inputmask.date.extensions'
import 'modules/admin-lte/plugins/input-mask/jquery.inputmask.extensions'

import 'modules/font-awesome/css/font-awesome.min.css'
import 'modules/ionicons/dist/css/ionicons.min.css'
import 'modules/admin-lte/bootstrap/css/bootstrap.min.css'
import 'modules/admin-lte/dist/css/AdminLTE.min.css'
import 'modules/admin-lte/dist/css/skins/_all-skins.min.css'
import 'modules/admin-lte/plugins/iCheck/flat/blue.css'
import 'modules/admin-lte/plugins/select2/select2.min.css'
import 'modules/admin-lte/plugins/select2/select2.min.css'
import 'modules/admin-lte/plugins/datatables/dataTables.bootstrap.css'
import 'modules/admin-lte/plugins/datepicker/datepicker3.css'
import 'modules/admin-lte/plugins/colorpicker/bootstrap-colorpicker.min.css'

import './custom.css'